# Generated by Django 3.2.6 on 2021-12-01 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateTimeField(verbose_name='Yoklama Tarihi'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson', verbose_name='Ders Adi'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_name',
            field=models.CharField(max_length=50, verbose_name='Ders Adi'),
        ),
    ]
