# Generated by Django 3.2.6 on 2021-12-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20211201_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.CharField(max_length=250, null=True, verbose_name='Ders Aciklamasi'),
        ),
    ]
